name: ExpressJsMySQL
services:
  backend: 
    build:
      context: ./app
      dockerfile: Containerfile
    image: expressjs
    ports:
      - "8000:3000"
    container_name: expressjs
    networks:
      - backend
    depends_on:
      db:
        condition: service_started
        restart: true
  db:
    image: mysql:lts-oraclelinux9
    container_name: mysql_db_express
    ports:
      - "8001:5432"
    networks:
      - backend
    volumes:
      - db-mysql-express:/etc/data
    environment:
      MYSQL_TCP_PORT: 5432
      MYSQL_HOST: express_mysql_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  db-visor:
    image: adminer
    container_name: adminer_express
    ports:
      - "8002:8080"
    networks:
      - backend
    depends_on:
      db:
        condition: service_started
        restart: true
    environment:
      ADMINER_PLUGIN: 'table-indexes-structure tables-filter tinymce'
      ADMINER_DESIGN: 'dracula'
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_USER: admin
      ADMINER_DEFAULT_USER_PASSWORD: root
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_DB_NAME: express_db

volumes:
  db-mysql-express:

networks:
  backend:
    name: backend-network
    external: true
